### ISSUE TITLE
初使用

### ISSUE THREAD

**Issue by Sylviandy** [kiroshiime/kiroshiimeNote#1]
1.右键拖动崩溃，可以考虑使用以下方式替换原来的DragMove()方法：
//DragMove();
try{ this.DragMove(); } catch{}
2.字符集问题，在我的系统中特殊字符显示为口口，是xaml中定义特殊字符的问题
暂且如上，其他待发现

**Comment by kiroshiime** [comment]
非常感谢汇报此bug。我会修复的
